apply plugin: 'com.android.application'

android {
    compileSdkVersion 37
    namespace = "com.gemalto.wsq.test"



    defaultConfig {
        applicationId "com.gemalto.wsq.test"
        minSdkVersion 16
        targetSdkVersion 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }

    signingConfigs {
        release {
            //TODO update the path to your keystore and the related variables
            if (project.hasProperty('defaultKeyStoreFile')) storeFile file(defaultKeyStoreFile)
            if (project.hasProperty('defaultKeyStorePassword')) storePassword defaultKeyStorePassword
            if (project.hasProperty('defaultKeyAlias')) keyAlias defaultKeyAlias
            if (project.hasProperty('defaultKeyPassword')) keyPassword defaultKeyPassword
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':wsq-android')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.core:core:1.12.0'
}
